defaults:
    - base_llm

name: "mistralai/Mistral-7B-Instruct-v0.2"
model_params: 
    max_model_len: 10000
chat_template: >
    "{%- for message in messages %} \
        {%- if message['role'] == 'system' -%} \
            {{- message['content'] -}}
        {%- else -%}
            {%- if message['role'] == 'user' -%}
                {{-'[INST] ' + message['content'].rstrip() + ' [/INST]'-}}
            {%- else -%}
                {{-'' + message['content'] + '</s>' -}}
            {%- endif -%}
        {%- endif -%}
    {%- endfor -%}
    {%- if add_generation_prompt -%}
        {{-''-}}
    {%- endif -%}"