defaults:
  - base_env
id: "worldllm_envs/PlaygroundText-v1"
kwargs:
  max_steps: 30

rule: "Grow any big_herbivorous"

test_trajectories:
  - [
      "You see the carrot seed, the water, the pea seed, the water and the baby cow. You are standing on nothing. Your are holding nothing.",
      "You go to the water.",
      "You are standing on water",
      "You pick up the object.",
      "You are holding the water.",
      "You go to the pea seed.",
      "You are standing on pea seed",
      "You give the water.",
      "The pea seed grows into the pea.",
    ]
  - [
      "You see the baby sheep, the water, the berry seed, the berry seed and the baby giraffe. You are standing on nothing. Your are holding nothing.",
      "You go to the water.",
      "You are standing on water",
      "You pick up the object.",
      "You are holding the water.",
      "You go to the berry seed.",
      "You are standing on berry seed",
      "You give the water.",
      "The berry seed grows into the berry.",
      "You pick up the object.",
      "You are holding the berry.",
      "You go to the baby sheep.",
      "You are standing on baby sheep",
      "You give the berry.",
      "The baby sheep grows into the sheep.",
    ]
  - [
      "You see the baby rhinoceros, the water, the potato seed, the water and the carrot seed. You are standing on nothing. Your are holding nothing.",
      "You go to the water.",
      "You are standing on water",
      "You pick up the object.",
      "You are holding the water.",
      "You go to the carrot seed.",
      "You are standing on carrot seed",
      "You give the water.",
      "The carrot seed grows into the carrot.",
      "You pick up the object.",
      "You are holding the carrot.",
      "You go to the water.",
      "You are standing on water",
      "You pick up the object.",
      "You are holding the carrot and the water.",
      "You go to the potato seed.",
      "You are standing on potato seed",
      "You give the water.",
      "The potato seed grows into the potato.",
      "You pick up the object.",
      "You are holding the carrot and the potato.",
      "You go to the baby rhinoceros.",
      "You are standing on baby rhinoceros",
      "You give all the objects you hold.",
      "The baby rhinoceros grows into the rhinoceros.",
    ]
  - [
      "You see the baby giraffe, the water, the potato seed, the water and the beet seed. You are standing on nothing. Your are holding nothing.",
      "You go to the water.",
      "You are standing on water",
      "You go to the beet seed.",
      "You are standing on beet seed",
      "You go to the water.",
      "You are standing on water",
      "You go to the water.",
      "Nothing has changed.",
      "You go to the beet seed.",
      "You are standing on beet seed",
      "You pick up the object.",
      "You are holding the beet seed.",
      "You give the beet seed.",
      "Nothing has changed.",
      "You go to the water.",
      "You are standing on water",
      "You pick up the object.",
      "You are holding the beet seed and the water.",
      "You go to the baby giraffe.",
      "You are standing on baby giraffe",
      "You go to the baby giraffe.",
      "Nothing has changed.",
      "You pick up the object.",
      "Nothing has changed.",
      "You pick up the object.",
      "Nothing has changed.",
      "You go to the water.",
      "You are standing on water",
      "You go to the baby giraffe.",
      "You are standing on baby giraffe",
      "You go to the potato seed.",
      "You are standing on potato seed",
      "You go to the potato seed.",
      "Nothing has changed.",
      "You give the water.",
      "The potato seed grows into the potato.",
      "You pick up the object.",
      "You are holding the beet seed and the potato.",
      "You give the potato.",
      "Nothing has changed.",
    ]
  - [
      "You see the beet seed, the water, the baby pig, the potato seed and the baby cow. You are standing on nothing. Your are holding nothing.",
      "You go to the beet seed.",
      "You are standing on beet seed",
      "You go to the baby cow.",
      "You are standing on baby cow",
      "You go to the baby pig.",
      "You are standing on baby pig",
      "You go to the beet seed.",
      "You are standing on beet seed",
      "You go to the beet seed.",
      "Nothing has changed.",
      "You pick up the object.",
      "You are holding the beet seed.",
      "You go to the potato seed.",
      "You are standing on potato seed",
      "You go to the potato seed.",
      "Nothing has changed.",
      "You go to the baby cow.",
      "You are standing on baby cow",
      "You go to the potato seed.",
      "You are standing on potato seed",
      "You give the beet seed.",
      "Nothing has changed.",
      "You go to the water.",
      "You are standing on water",
      "You pick up the object.",
      "You are holding the beet seed and the water.",
      "You go to the baby pig.",
      "You are standing on baby pig",
      "You give the beet seed.",
      "Nothing has changed.",
      "You go to the baby cow.",
      "You are standing on baby cow",
      "You give the beet seed.",
      "Nothing has changed.",
      "You go to the potato seed.",
      "You are standing on potato seed",
      "You give all the objects you hold.",
      "Nothing has changed.",
      "You go to the potato seed.",
      "Nothing has changed.",
    ]
