defaults: 
  - base_config
  - algorithm: importance_sampling
  - llm@theorist: Phi-3-mini-4k-instruct
  - llm@statistician: Phi-3-mini-4k-instruct
  - environment: door
  - agent: all
  
exp_name: test_is

statistician: null
seed: 60
algorithm:
  nb_rules: 100
