defaults: 
  - base_config
  - algorithm: importance_sampling
  - llm@theorist: llama-3-8b-instruct.yaml
  - llm@statistician: llama-3-8b-instruct.yaml
  - environment: door
  - agent: random
  
exp_name: test_is

statistician: null
seed: 60
algorithm:
  nb_rules: 100
