defaults: 
  - algorithm: importance_sampling
  - llm@theorist: llama-3-8b-instruct.yaml
  - llm@statistician: llama-3-8b-instruct.yaml
  - env: door
  - agent: random

statistician: null
seed: 60
algorithm:
  nb_rules: 100
