defaults: 
  - base_config
  - algorithm: importance_sampling
  - llm@theorist: llama-3-8b-instruct.yaml
  - llm@statistician: Phi-3-mini-4k-instruct
  - environment: door
  - agent: random


exp_name: test_is_llama_phi
seed: 60
algorithm:
  nb_rules: 100
  stat_batch_size: 50
  th_batch_size: 20
