defaults: 
  - algorithm: importance_sampling
  - llm@theorist: llama-3-8b-instruct.yaml
  - llm@statistician: Phi-3-mini-4k-instruct
  - environment: door
  - agent: random
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .


seed: 60
algorithm:
  nb_rules: 100
  stat_batch_size: 50
  th_batch_size: 20
