defaults: 
  - base_config
  - algorithm: metropolis_hastings
  - llm@theorist: Phi-3-mini-4k-instruct
  - llm@statistician: Phi-3-mini-4k-instruct
  - environment: door
  - agent: all

exp_name: test_metropolis
statistician: null
seed: 50