defaults:
  - base_config
  - algorithm: importance_sampling
  - llm@theorist: Phi-3-mini-4k-instruct
  - llm@statistician: Phi-3-mini-4k-instruct
  - experimenter: perfectplayground
  - environment: playground

exp_name: test_playground

statistician: null
seed: 60
algorithm:
  nb_rules: 100
  stat_batch_size: 5
  th_batch_size: 1
  nb_trajectories: 6
  add_true_rule: False
  add_without_rule: true
